name 'buildkite_agent'
maintainer 'Greg Schofield'
maintainer_email 'greg.c.schofield@gmail.com'
license 'MIT'
description 'Installs and configures a buildkite agent'
version '0.1.1'
chef_version '>= 14.0'

issues_url 'https://github.com/gscho/buildkite_agent/issues'
source_url 'https://github.com/gscho/buildkite_agent'
